apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: arc-runners
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - name: taskteck
          - list:
              elements:
              - cluster: in-cluster
                cluster-url: https://kubernetes.default.svc
                prefix: gha-runner-scale-set-controller
                environment: stg
                flavour: small
  template:
    metadata:
      name: '{{name}}-runners-{{environment}}-{{flavour}}'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
      - repoURL: 'https://github.com/taskteck/kubernetes-poc.git'
        targetRevision: 'dev'
        ref: values
      - repoURL: 'https://github.com/taskteck/kubernetes-poc.git'
        targetRevision: 'dev'
        path: assets/gha-runner-scale-set-stne/helm
        helm:
          parameters:
          - name: runnerScaleSet.githubConfigUrl
            value: "https://github.com/taskteck"
          - name: runnerScaleSet.runnerScaleSetName
            value: "{{ flavour }}-runner-scale-set-{{ environment }}"
          - name: runnerScaleSet.githubConfigSecret
            value: gh-runners-secret
          valueFiles:
          - '$values/applications.d/gha-runner-scale-set/values.yaml'
      destination:
        name: '{{ cluster }}'
        namespace: 'arc-runners'
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
