name: Stress Test for Self-Hosted Runners

on: [workflow_dispatch]

jobs:
  stress-test:
    runs-on: "small-runner-scale-set-stg"
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install stress-ng
        run: |
          sudo apt-get update

      - run: sleep 10

